# Generated by Django 4.1.3 on 2022-11-25 07:09

import versatileimagefield.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("web", "0002_applynow")]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=200)),
                ("image", versatileimagefield.fields.VersatileImageField(upload_to="images/team/", verbose_name="Image")),
            ],
        )
    ]
