# Generated by Django 4.1.3 on 2022-11-26 06:13

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDigitalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Category Digital Media',
            },
        ),
        migrations.CreateModel(
            name='DesignDigitalMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/digitalmedia/', verbose_name='Image')),
                ('media_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.categorydigitalmedia')),
            ],
            options={
                'verbose_name_plural': 'Digital Media',
            },
        ),
    ]
