# Generated by Django 4.1.3 on 2022-11-26 06:26

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_categorydigitalmedia_designdigitalmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgageDataService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='images/imagedataservice/', verbose_name='Image')),
                ('title', models.CharField(max_length=200)),
                ('details', models.TextField()),
            ],
        ),
    ]
